[workspace]
members = [ "node" ]

[package]
name = "tauri-cli"
version = "1.6.4"
authors = [ "Tauri Programme within The Commons Conservancy" ]
edition = "2021"
rust-version = "1.71"
categories = [ "gui", "web-programming" ]
license = "Apache-2.0 OR MIT"
homepage = "https://tauri.app"
repository = "https://github.com/tauri-apps/tauri"
description = "Command line interface for building Tauri apps"
include = [
  "src/",
  "/templates",
  "scripts/",
  "*.json",
  "*.rs",
  "tauri.gitignore",
  "tauri-dev-watcher.gitignore",
  "LICENSE*"
]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/tauri-cli-v{ version }/cargo-tauri-{ target }.{ archive-format }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"

[package.metadata.binstall.overrides.x86_64-apple-darwin]
pkg-fmt = "zip"

[[bin]]
name = "cargo-tauri"
path = "src/main.rs"

[dependencies]
clap_complete = "4"
clap = { version = "4.4", features = [ "derive" ] }
anyhow = "1.0"
tauri-bundler = { version = "1.7.2", path = "../bundler", default-features = false }
colored = "2.0"
once_cell = "1"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
notify = "6.1"
notify-debouncer-mini = "0.4"
shared_child = "1.0"
toml_edit = "0.22"
json-patch = "2"
tauri-utils = { version = "1.6.1", path = "../../core/tauri-utils", features = [ "isolation", "schema", "config-json5", "config-toml" ] }
toml = "0.8"
jsonschema = { version = "0.18", default-features = false }
handlebars = "4.4"
include_dir = "0.7"
minisign = "=0.7.3"
base64 = "0.22.1"
ureq = { version = "2.9.1", default-features = false, features = [ "gzip" ] }
os_info = "3"
semver = "1.0"
regex = "1.10.2"
unicode-width = "0.1"
zeroize = "1.6"
heck = "0.5"
dialoguer = "0.11"
url = { version = "2.4", features = [ "serde" ] }
os_pipe = "1"
ignore = "0.4"
ctrlc = "3.4"
log = { version = "0.4.21", features = [ "kv", "kv_std" ] }
env_logger = "0.10.0"
icns = { package = "tauri-icns", version = "0.1" }
image = { version = "0.25", default-features = false, features = [ "ico" ] }
axum = { version = "0.7.0", features = [ "ws" ] }
html5ever = "0.26"
kuchiki = { package = "kuchikiki", version = "0.8" }
tokio = { version = "1", features = [ "macros", "sync" ] }
common-path = "1"
serde-value = "0.7.0"
itertools = "0.13"
glob = "0.3"
dunce = "1"

[target."cfg(windows)".dependencies]
winapi = { version = "0.3", features = [ "handleapi", "processenv", "winbase", "wincon", "winnt" ] }
cc = "1"

[target."cfg(unix)".dependencies]
libc = "0.2"

[profile.release]
lto = true

[features]
default = [ "rustls" ]
native-tls = [ "tauri-bundler/native-tls", "ureq/native-tls" ]
native-tls-vendored = [ "native-tls", "tauri-bundler/native-tls-vendored" ]
rustls = [ "tauri-bundler/rustls", "ureq/tls" ]
