name: Build and Test EXE for TestDriver

env:
  DEBUG: napi:*

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    name: Build Windows EXE
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          architecture: x64
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - name: Install dependencies (clean)
        run: |
          cd examples/api
          rm -rf node_modules pnpm-lock.yaml  # Clean old dependencies
          pnpm install --prod --frozen-lockfile --ignore-scripts
      - name: Install Tauri CLI
        run: |
          cd examples/api
          pnpm add @tauri-apps/cli -D
      - name: Build API Example App
        run: |
          cd examples/api
          pnpm tauri build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-app
          path: examples/api/src-tauri/target/release/app.exe
          if-no-files-found: error

  testdriver_matrix:
    name: "TestDriver Matrix"
    needs: build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        test:
          - name: "Call Log API testdriver"
            file: "testdriver/comm_call_log_api.yml"
          - name: "Call Request API testdriver"
            file: "testdriver/comm_call_request_api.yml"
          - name: "Echo testdriver"
            file: "testdriver/comm_echo.yml"
          - name: "Send Event to Rust testdriver"
            file: "testdriver/comm_send_event_rust.yml"
          - name: "Spam testdriver"
            file: "testdriver/comm_spam.yml"
    steps:
      - name: Download Built App
        uses: actions/download-artifact@v4
        with:
          name: tauri-app
          path: ${{ runner.temp }}/tauri-app

      - name: Verify and Launch Application
        shell: pwsh
        run: |
          $exePath = "${{ runner.temp }}\tauri-app\app.exe"
          if (Test-Path $exePath) {
              Write-Host "✅ Executable found at: $exePath"
              Unblock-File -Path $exePath
              Write-Host "🚀 Launching application..."
              
              # Run process and keep it open for testing
              $process = Start-Process -FilePath $exePath -NoNewWindow -PassThru
              
              Start-Sleep -Seconds 5  # Give time for startup
              if ($process.HasExited) {
                  Write-Error "❌ The application exited unexpectedly."
                  exit 1
              } else {
                  Write-Host "✅ Application is running successfully."
              }
          } else {
              Write-Error "❌ Executable not found."
              exit 1
          }
      - name: Run TestDriver Tests
        uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: |
            1. /run ${{ matrix.test.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"

