name: Build EXE for TestDriver
env:
  DEBUG: napi:*

on:
  pull_request:

jobs:
  build:
    name: build windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          architecture: x64
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - name: Install dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts
      - name: Build CLI
        run: pnpm run build:cli
        shell: bash
      - name: Build API
        run: pnpm run build:api
        shell: bash
      - name: Build API Example App
        run: |
          cd examples/api
          pnpm tauri build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-x86_64-pc-windows-msvc
          path: target\release\bundle\nsis\*
          if-no-files-found: error
      - name: Fetch artifact URL
        run: |
          echo "Fetching artifact URL..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" \
               | jq '.artifacts[0].archive_download_url'
      - uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          prompt: | 
            1. Click around the desktop app
          prerun: |
            $headers = @{
                Authorization = "token ${{ secrets.GITHUB_TOKEN }}"
            }
            $downloadFolder = "./download"
            $artifactFileName = "waveterm.exe"
            $artifactFilePath = "$downloadFolder/$artifactFileName"
            Write-Host "Starting the artifact download process..."
            if (-not (Test-Path -Path $downloadFolder)) {
                mkdir $downloadFolder
            }
            Write-Host "Fetching the artifact upload URL..."
            $artifactResponse = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" -Headers $headers
            if ($artifactResponse.artifacts.Count -gt 0) {
                $artifactUrl = $artifactResponse.artifacts[0].archive_download_url
                Write-Host "Artifact URL: $artifactUrl"
            } else {
                Write-Error "No artifacts found."
                exit 1
            }
            $artifactZipPath = "$env:TEMP\artifact.zip"
            try {
                Invoke-WebRequest -Uri $artifactUrl -Headers $headers -OutFile $artifactZipPath -MaximumRedirection 5
                Write-Host "Artifact downloaded successfully."
            } catch {
                Write-Error "Error downloading artifact: $_"
                exit 1
            }
            $artifactUnzipPath = "$env:TEMP\artifact"
            Expand-Archive -Path $artifactZipPath -DestinationPath $artifactUnzipPath -Force
            $artifactInstallerPath = Get-ChildItem -Path $artifactUnzipPath -Filter *.exe -Recurse | Select-Object -First 1
            if ($artifactInstallerPath) {
                Write-Host "Executable found: $($artifactInstallerPath.FullName)"
                Start-Process -FilePath $artifactInstallerPath.FullName -Wait
            } else {
                Write-Error "Executable not found."
                exit 1
            }
            $wavePath = Join-Path $env:USERPROFILE "AppData\Local\Programs\waveterm\Wave.exe"
            Start-Process -FilePath $wavePath
            Write-Host "Application launched."
